### ISSUE TITLE
Can't get type declarations to work in ES Module project

### ISSUE THREAD

**Issue by DaniDipp** [pocketbase/js-sdk#92]
I've read a bunch of other issues which gave me the impression that with the `"type": "module"` setup, it should work out of the box, but I'm clearly doing something else wrong. 

The warning on the import statement is:
```
Could not find a declaration file for module 'pocketbase'. 's:/New folder (5)/pocketbase/node_modules/pocketbase/dist/pocketbase.es.mjs' implicitly has an 'any' type.
```

![2022-11-30T22-21-54](https://user-images.githubusercontent.com/17002453/204911758-ae82d2f7-c13f-4978-ab1c-244f4ef81203.png)
Thanks in advance for any help with this.

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce the issue (with the standard LSP plugins for sublime and vim).

The types are linked in the [package.json](https://github.com/pocketbase/js-sdk/blob/master/package.json#L19).

It could be a cache, I'm not sure. You could try checking if you have `node_modules/pocketbase/pocketbase.es.d.ts` file.

Did you try restarting your LSP server (or the editor)?

**Comment by ganigeorgiev** [comment]
@DaniDipp Eventually you could try adding `"allowJs": true` inside your `compilerOptions` in case the tsc is looking only for ts/tsx files.

**Comment by DaniDipp** [comment]
Yeah, I restarted the LSP and VSCode, tried it in WSL and in Windows.
`"allowJs": true` doesn't change it.

I installed Sublime and the TS Language Server plugin and there it works, so it seems to be a VSCode issue...

**Comment by DaniDipp** [comment]
Solved. The culprit was `"moduleResolution": "NodeNext"`. Downgrading it to `"moduleResolution": "Node"` made it work correctly.

`tsconfig.json`
```json
{
	"compilerOptions": {
		"module": "ESNext",
		"moduleResolution": "Node",
		"target": "ESNext",
		"sourceMap": true,
		"outDir": "dist",
	},
	"include": ["src/**/*"]
}
```

**Comment by DaniDipp** [comment]
Can you reproduce it with `"strict": true`?

```json
{
	"compilerOptions": {
		"module": "ESNext",
		"moduleResolution": "NodeNext",
		"target": "ESNext",
		"sourceMap": true,
		"outDir": "dist",
		"strict": true
	},
	"include": ["src/**/*"]
}
```

**Comment by ganigeorgiev** [comment]
@DaniDipp It works fine for me. Also please note that we have `strict` enabled - https://github.com/pocketbase/js-sdk/blob/master/tsconfig.json#L8.

What is the `tsc` error you are getting?

**Comment by DaniDipp** [comment]
Damn, ok.

The compile error is the same as the warning before strict mode:
```
src/app.ts:1:24 - error TS7016: Could not find a declaration file for module 'pocketbase'. '/mnt/s/New folder (5)/pocketbase/node_modules/pocketbase/dist/pocketbase.es.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/pocketbase` if it exists or add a new declaration (.d.ts) file containing `declare module 'pocketbase';`

1 import PocketBase from "pocketbase";
                         ~~~~~~~~~~~~
```

**Comment by ganigeorgiev** [comment]
@DaniDipp I'm not sure why it doesn't work in your case.

Could you confirm that you are using TS 4.7+?

From the [official release docs](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing):

> For example, if "main" pointed to ./lib/index.js, TypeScript would look for a file called ./lib/index.d.ts. A package author could override this by specifying a separate field called "types" (e.g. "types": "./types/index.d.ts").

It seems that in your case the SDK's package.json `types` property is ignored for some reason.

**Comment by ganigeorgiev** [comment]
This is probably related to https://github.com/microsoft/TypeScript/issues/13627.

You can try enabling `"esModuleInterop": true` and see if that will make any difference.

**Comment by ganigeorgiev** [comment]
It is also possible that TS is looking for `.mts` ending definition file since the exported has `.mjs` extension, or in other words you can test renaming the definition file to `.mts`.

**Comment by DaniDipp** [comment]
This is it! With `.d.mts` I get no more warnings and errors in the IDE or during compilation.

**Comment by ganigeorgiev** [comment]
Hm, I'll investigate it later this week and eventually will change it but it is possible that this could be an upstream bug (my local lsp-typescript is using ts 4.8 and the extension doesn't matter as long as the `types` property is set).

**Comment by DaniDipp** [comment]
Thank you so much!

I don't know what's wrong with my setup. Maybe you can reproduce it with Docker?

```Dockerfile
FROM node:alpine

WORKDIR /test

RUN echo $'{\n\
  "type": "module"\n\
}' > package.json;

RUN npm install typescript pocketbase

RUN echo $'{\n\
  "compilerOptions": {\n\
    "module": "ESNext",\n\
    "moduleResolution": "NodeNext",\n\
    "target": "ESNext",\n\
    "strict": true,\n\
  },\n\
  "include": ["*.ts"]\n\
}' > tsconfig.json;

RUN echo $'\n\
import PocketBase from "pocketbase";\n\
const pocketbase = new PocketBase("http://localhost:8090");\n\
'> app.ts;

RUN npx tsc
```

**Comment by ganigeorgiev** [comment]
I think I found the related TS issue - https://github.com/microsoft/TypeScript/issues/50762.

It seems that the problem is with how the `exports` is resolved and ts for some reason makes a guess where the declaration file is located instead of loading it directly from the `types` prop (either in the root level or as part of an `exports` block).

I'll reopen the issue and will update sometime later the file extension to generate it with `.mts`.

**Comment by ganigeorgiev** [comment]
The "fix" should be available with the v0.8.3 release.

**Comment by olestole** [comment]
Encountered this issue with pocketbase v.0.9.1. 

**Resolved** by updating TS to v4.9.4, as mentioned by @ganigeorgiev.

**Comment by ilearnio** [comment]
I still have this issue. Tried to use latest TypeScrip 5+ and 4.9.4

![image](https://github.com/pocketbase/js-sdk/assets/14331216/f5bc91ce-93cc-4750-9cb8-a88e84446921)

**Comment by g1sbi** [comment]
I also still have this issue in a node server.

ts-node version: 10.9.1
pocketbase: 0.15.2

tsconfig:
```json
{
 "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist", 
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "allowJs": true
  }
}
```

**Comment by yarelyGE** [comment]
Hi, I'm starting a project in Angular with Pocketbase. When I compile it, I get the same error. I have applied the solutions that were previously mentioned, but it doesn't work. The version of Node is v16.14.0 and the version of Pocketbase is 0.22.17.
![image](https://github.com/user-attachments/assets/c0cdb22d-123e-4568-aa94-1dd9e95c6207)
